version: '3'
services:
  web:
    image: httpd:latest
    ports:
      - "8000:80"
    volumes:
      - ./apache/src:/usr/local/apache2/htdocs/
    depends_on:
      - db
      - api

  db:
    build: ./mariadb/
    restart: always
    volumes:
      - ./mariadb/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./mariadb/data/:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - "8889:3306"
    
  api:
    build: api/
    ports:
      - "5001:5001"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db    
    environment:
      WAIT_HOSTS: db:3306
    env_file:
      - ./.env

  scraper:
    build: scraper/
    volumes:
      - ./scraper:/usr/src/app
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306
    env_file:
      - ./.env

  nginxgateway:
    build: ./nginx/
    ports:
      - "80:80"
      #- "443:443"
    #volumes:
     # - ./nginx:/etc/nginx/conf.d
    restart: always
    depends_on:
      - db
      - api
      - web
  #certbot:
  #  image: certbot/certbot
