version: '3'
services:
  web:
    build: ./online/apache
    ports:
      - "8000:80"
    volumes:
      - ./online/apache/src:/var/www/html
    depends_on:
      - db

  db:
    build: ./online/mariadb/
    restart: always
    volumes:
      - ./online/mariadb/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: admin
      MYSQL_PASSWORD: test 
    ports:
      - "8889:3306"
    
