version: '3'
services:
  web:
    image: php:7.4-apache
    ports:
      - "8000:80"
    volumes:
      - ./online/apache/src:/var/www/html
    depends_on:
      - db
      - pythonapi

  db:
    build: ./online/mariadb/
    restart: always
    volumes:
      - ./online/mariadb/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
     # - ./online/mariadb/data/:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      #MYSQL_USER: admin
      #MYSQL_PASSWORD: test 
      #MYSQL_DATABASE: luhze
    ports:
      - "8889:3306"
    
  pythonapi:
    build: ./online/pythonAPI/
    ports:
      - "5001:5001"
    volumes:
      - ./online/pythonAPI:/usr/src/app
    depends_on:
      - db    
    environment:
      WAIT_HOSTS: db:3306

  pythongather:
    build: ./online/pythonGather/
    volumes:
      - ./online/pythonGather:/usr/src/app
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306

  nginxgateway:
    build: ./online/nginx/
    ports:
      - "80:80"
      #- "443:443"
    #volumes:
     # - .online/nginx:/etc/nginx/conf.d
    restart: always
    depends_on:
      - db
      - pythonapi
      - web
  #certbot:
  #  image: certbot/certbot

#  pythonanalyze:
 #   build: ./online/pythonAnalyze/
  #  volumes:
   #   - ./online/pythonAnalyze:/usr/src/app
   # depends_on:
     # - db
    #environment:
     # WAIT_HOSTS: db:3306
