FROM mariadb:10.5
#RUN apt-get update
#RUN apt-get install -y sed
#COPY ./schema.sql /docker-entrypoint-initdb.d/schema.sql
#RUN sed -i 's/${MYSQL_USER_API}/'"${MYSQL_USER_API}"'/g' /docker-entrypoint-initdb.d/schema.sql
#RUN sed -i 's/${MYSQL_USER_GATHERER}/'"${MYSQL_USER_GATHERER}"'/g' /docker-entrypoint-initdb.d/schema.sql
#RUN sed -i 's/${MYSQL_PASSWORD_API}/'"${MYSQL_PASSWORD_API}"'/g' /docker-entrypoint-initdb.d/schema.sql
#RUN sed -i 's/${MYSQL_PASSWORD_GATHERER}/'"${MYSQL_PASSWORD_GATHERER}"'/g' /docker-entrypoint-initdb.d/schema.sql
#RUN cat /docker-entrypoint-initdb.d/schema.sql
#COPY ./data /var/lib/mysql
