FROM python:3.7-buster
COPY . /usr/src/app
RUN apt-get update && apt-get install cron -y
ADD crontab /etc/cron/scrape
RUN chmod 0644 /etc/cron.d/scrape
RUN crontab /etc/cron.d/scrape
CMD ["cron","-f"]
