name: Deploy to VPS

on:
  push:
    branches:
      - fix_actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOME_PATH: test

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "TSET"

