name: Deploy to VPS

on:
  push:
    branches:
      - fix_actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: ${{ secrets.PATH }}
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "PATH is ${PROJECT_PATH}"
            echo "TEST"

